### ISSUE TITLE
Deadlock in version 2.7

### ISSUE THREAD

**Issue by zzkp2012** [kamranzafar/JCL#50]
thread busy-map-server-莲花洞-6-0:
`java.lang.Thread.State: BLOCKED
    at java.lang.ClassLoader.checkCerts(ClassLoader.java:884)
    - waiting to lock <13bdd6ad> (a org.xeustechnologies.jcl.JarClassLoader) owned by "login-executor-0" t@301
    at java.lang.ClassLoader.preDefineClass(ClassLoader.java:665)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:758)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
    at org.xeustechnologies.jcl.JarClassLoader.access$000(JarClassLoader.java:42)
    at org.xeustechnologies.jcl.JarClassLoader$LocalLoader.loadClass(JarClassLoader.java:246)
    at org.xeustechnologies.jcl.AbstractClassLoader.loadClass(AbstractClassLoader.java:120)
    - locked <789824e1> (a java.util.Collections$SynchronizedRandomAccessList)
    at org.xeustechnologies.jcl.AbstractClassLoader.loadClass(AbstractClassLoader.java:94)
    at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:376)
    at org.reflections.ReflectionUtils.forNames(ReflectionUtils.java:397)
    at org.reflections.Reflections.getSubTypesOf(Reflections.java:367)

 Locked ownable synchronizers:
    - locked <12e5f7cb> (a java.util.concurrent.ThreadPoolExecutor$Worker)`

thread login-executor-0:
`java.lang.Thread.State: BLOCKED
    at org.xeustechnologies.jcl.AbstractClassLoader.loadClass(AbstractClassLoader.java:117)
    - waiting to lock <789824e1> (a java.util.Collections$SynchronizedRandomAccessList) owned by "busy-map-server-莲花洞-6-0" t@205
    at org.xeustechnologies.jcl.AbstractClassLoader.loadClass(AbstractClassLoader.java:94)

   JNI locked monitors:
    - locked <13bdd6ad> (a org.xeustechnologies.jcl.JarClassLoader)

   Locked ownable synchronizers:
    - locked <33c6c4f> (a java.util.concurrent.ThreadPoolExecutor$Worker)`

any suggestion?

**Comment by fxgendrin** [comment]
Get the same with a deadlock with 2 threads: one has the lock on instance of the classloader and wants lock on AbstractClassLoader.loaders, the other the inverse. 

Need a new release with following modification in AbstractClassLoader (as suggested in comment, but need to be compatible only with java 1.6, alternative is to duplicate ConcurrentSkipListSet into the project)
`protected final Set<ProxyClassLoader> loaders = new ConcurrentSkipListSet<ProxyClassLoader>();
`
